name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  lintRelease:
    runs-on: macos-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: Checkout
        uses: actions/checkout@v3
      - name: Access secret
        env:
          OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
          UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}
        run: |
          echo OPENWEATHER_KEY=OPENWEATHER_KEY > ./local.properties
          echo UNSPLASH_KEY=UNSPLASH_KEY >> ./local.properties
      - name: Build
        run: ./gradlew lintRelease
  test:
    runs-on: macos-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: Checkout
        uses: actions/checkout@v3
      - name: Access secret
        env:
          OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
          UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}
        run: |
          echo OPENWEATHER_KEY=OPENWEATHER_KEY > ./local.properties
          echo UNSPLASH_KEY=UNSPLASH_KEY >> ./local.properties
      - name: Test
        run: ./gradlew testDebugUnitTest
